"""Writer Agent - produces the final polished report."""

from datetime import datetime

from deep_research_agent.core.state import ResearchState
from deep_research_agent.core.router import router, ModelTier


def writer_node(state: ResearchState) -> ResearchState:
    """Writer Agent node.

    Produces the final polished research report by assembling
    synthesized sections with proper formatting.

    Args:
        state: Current research state

    Returns:
        Updated state with final report
    """
    if not state.sections:
        state.add_log("ERROR", "No sections to write report from", agent="writer")
        state.report = f"# Error\n\nNo content generated for query: {state.query}"
        return state

    try:
        # Get model for strong tier (executive summary only)
        model, config = router.get_model(ModelTier.STRONG)

        # Build report body from existing sections
        body_sections = []
        for s in sorted(state.sections, key=lambda x: x.order):
            # Clean up any remaining "Section Title:" artifacts
            content = s.content
            if content.startswith(f"{s.title}"):
                content = content[len(s.title):].lstrip("\n: ")
            body_sections.append(f"## {s.title}\n\n{content}")

        body = "\n\n".join(body_sections)

        # Generate executive summary using LLM
        summary_prompt = f"""Based on the following research sections, write a concise executive summary (2-3 paragraphs) highlighting the key findings:

{body[:2000]}

Executive Summary:"""

        summary_response = model.invoke(summary_prompt)
        summary = summary_response.content if hasattr(summary_response, 'content') else str(summary_response)
        summary = summary.strip()

        # Generate conclusion
        conclusion_prompt = f"""Based on the following research, write a brief conclusion (1 paragraph) synthesizing the key takeaways:

{body[:2000]}

Conclusion:"""

        conclusion_response = model.invoke(conclusion_prompt)
        conclusion = conclusion_response.content if hasattr(conclusion_response, 'content') else str(conclusion_response)
        conclusion = conclusion.strip()

        # Build table of contents
        toc = "\n".join([
            f"{i+1}. [{s.title}](#{s.title.lower().replace(' ', '-')})"
            for i, s in enumerate(sorted(state.sections, key=lambda x: x.order))
        ])

        # Build references
        references = "\n".join([
            f"{i+1}. [{s.title}]({s.url})"
            for i, s in enumerate(state.sources[:20])  # Limit to top 20
        ]) if state.sources else "No sources available."

        # Assemble final report
        title = f"Research Report: {state.query[:50]}{'...' if len(state.query) > 50 else ''}"

        report_parts = [
            f"# {title}",
            "",
            f"> **Research Query:** {state.query}",
            f"> **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            f"> **Research Iterations:** {state.iteration + 1}",
            f"> **Total Cost:** ${state.cost.total_cost_usd:.4f}",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            summary,
            "",
            "---",
            "",
            "## Table of Contents",
            "",
            toc,
            "",
            "---",
            "",
            body,
            "",
            "---",
            "",
            "## Conclusion",
            "",
            conclusion,
            "",
            "---",
            "",
            "## References",
            "",
            references,
            "",
            "---",
            "",
            f"*Generated by Deep Research Agent*",
            f"*Trace ID: {state.trace_id}*",
        ]

        state.report = "\n".join(report_parts)

        # Track cost
        total_input_tokens = (
            router.estimate_tokens(summary_prompt) +
            router.estimate_tokens(conclusion_prompt)
        )
        total_output_tokens = (
            router.estimate_tokens(summary) +
            router.estimate_tokens(conclusion)
        )
        cost = router.calculate_cost(config, total_input_tokens, total_output_tokens)
        state.cost.add_call(config.name, total_input_tokens, total_output_tokens, cost)
        state.cost.add_agent_cost("writer", cost)

        state.add_log(
            "INFO",
            f"Report generated. Length: {len(state.report)} chars, Cost: ${state.cost.total_cost_usd:.4f}",
            agent="writer",
            report_length=len(state.report),
        )

    except Exception as e:
        state.add_log("ERROR", f"Writer failed: {str(e)}", agent="writer")
        # Fallback: combine sections manually
        state.report = f"# Research Report: {state.query}\n\n" + "\n\n".join([
            f"## {s.title}\n\n{s.content}"
            for s in state.sections
        ])

    return state
