"""State management for Deep Research Agent."""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum
import uuid


class ReviewStatus(str, Enum):
    """Review status values."""

    PENDING = "pending"
    PASSED = "passed"
    FAILED = "failed"


@dataclass
class CostTracker:
    """Track token usage and costs."""

    input_tokens: int = 0
    output_tokens: int = 0
    total_cost_usd: float = 0.0
    calls_by_model: Dict[str, int] = field(default_factory=dict)
    cost_by_agent: Dict[str, float] = field(default_factory=dict)

    def add_call(self, model: str, input_tokens: int, output_tokens: int, cost_usd: float):
        """Record a model call."""
        self.input_tokens += input_tokens
        self.output_tokens += output_tokens
        self.total_cost_usd += cost_usd
        self.calls_by_model[model] = self.calls_by_model.get(model, 0) + 1

    def add_agent_cost(self, agent: str, cost: float):
        """Add cost for a specific agent."""
        self.cost_by_agent[agent] = self.cost_by_agent.get(agent, 0.0) + cost

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "total_cost_usd": round(self.total_cost_usd, 4),
            "calls_by_model": self.calls_by_model,
            "cost_by_agent": self.cost_by_agent,
        }


@dataclass
class Source:
    """Information source."""

    url: str
    title: str
    content: str
    relevance_score: float = 0.0
    retrieved_at: datetime = field(default_factory=datetime.now)
    query: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "url": self.url,
            "title": self.title,
            "content": self.content[:500] + "..." if len(self.content) > 500 else self.content,
            "relevance_score": round(self.relevance_score, 2),
            "retrieved_at": self.retrieved_at.isoformat(),
            "query": self.query,
        }


@dataclass
class ResearchPlan:
    """Research plan generated by Planner Agent."""

    strategy: str
    sub_queries: List[str]
    expected_sections: List[str]
    reasoning: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "strategy": self.strategy,
            "sub_queries": self.sub_queries,
            "expected_sections": self.expected_sections,
            "reasoning": self.reasoning,
        }


@dataclass
class Finding:
    """Research finding from Researcher Agent."""

    query: str
    sources: List[Source] = field(default_factory=list)
    summary: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "query": self.query,
            "sources_count": len(self.sources),
            "sources": [s.to_dict() for s in self.sources[:3]],  # Limit in output
            "summary": self.summary,
        }


@dataclass
class Section:
    """Report section from Synthesis Agent."""

    title: str
    content: str
    sources: List[str] = field(default_factory=list)
    order: int = 0

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "title": self.title,
            "content": self.content[:1000] + "..." if len(self.content) > 1000 else self.content,
            "sources": self.sources,
            "order": self.order,
        }


@dataclass
class ReviewFeedback:
    """Specific feedback item from Critic Agent."""

    dimension: str  # e.g., "completeness", "accuracy"
    issue: str
    severity: str  # "low", "medium", "high"
    suggestion: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "dimension": self.dimension,
            "issue": self.issue,
            "severity": self.severity,
            "suggestion": self.suggestion,
        }


@dataclass
class ReviewResult:
    """Review result from Critic Agent."""

    status: ReviewStatus
    score: float  # 0.0 to 1.0
    feedback: List[ReviewFeedback] = field(default_factory=list)
    revised_plan: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "status": self.status.value,
            "score": round(self.score, 2),
            "feedback": [f.to_dict() for f in self.feedback],
            "revised_plan": self.revised_plan,
        }


@dataclass
class LogEntry:
    """Log entry for execution tracking."""

    timestamp: datetime
    level: str
    agent: Optional[str]
    message: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ResearchState:
    """Main state class for the research workflow.

    This class holds all information flowing through the LangGraph pipeline.
    """

    # === Input ===
    query: str
    context: Optional[str] = None

    # === Execution Metadata ===
    trace_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    started_at: datetime = field(default_factory=datetime.now)
    iteration: int = 0

    # === Planning ===
    plan: Optional[ResearchPlan] = None

    # === Research ===
    findings: List[Finding] = field(default_factory=list)

    # === Synthesis ===
    sections: List[Section] = field(default_factory=list)

    # === Review ===
    review: Optional[ReviewResult] = None

    # === Output ===
    report: Optional[str] = None
    sources: List[Source] = field(default_factory=list)

    # === Tracking ===
    cost: CostTracker = field(default_factory=CostTracker)
    logs: List[LogEntry] = field(default_factory=list)

    # === Configuration ===
    max_iterations: int = 3

    def add_log(self, level: str, message: str, agent: Optional[str] = None, **kwargs):
        """Add a log entry."""
        entry = LogEntry(
            timestamp=datetime.now(),
            level=level,
            agent=agent,
            message=message,
            metadata=kwargs,
        )
        self.logs.append(entry)

    def get_all_sources(self) -> List[Source]:
        """Get all unique sources from findings."""
        seen = set()
        unique_sources = []
        for finding in self.findings:
            for source in finding.sources:
                if source.url not in seen:
                    seen.add(source.url)
                    unique_sources.append(source)
        return unique_sources

    def to_dict(self) -> Dict[str, Any]:
        """Convert state to dictionary for serialization."""
        return {
            "trace_id": self.trace_id,
            "query": self.query,
            "context": self.context,
            "started_at": self.started_at.isoformat(),
            "iteration": self.iteration,
            "plan": self.plan.to_dict() if self.plan else None,
            "findings_count": len(self.findings),
            "sections_count": len(self.sections),
            "review": self.review.to_dict() if self.review else None,
            "report_preview": self.report[:500] + "..." if self.report and len(self.report) > 500 else self.report,
            "sources_count": len(self.sources),
            "cost": self.cost.to_dict(),
            "max_iterations": self.max_iterations,
        }

    def is_complete(self) -> bool:
        """Check if research is complete."""
        return self.report is not None

    def should_continue(self) -> bool:
        """Check if research should continue (feedback loop)."""
        if self.iteration >= self.max_iterations:
            return False
        if self.review and self.review.status == ReviewStatus.PASSED:
            return False
        return True
