"""Writer Agent - produces the final polished report."""

from datetime import datetime

from src.core.state import ResearchState
from src.core.router import router, ModelTier


WRITER_PROMPT = """You are a professional research writer. Create a polished final report from the research sections.

Original Query: {query}

Sections to include:
{sections}

Instructions:
1. Create a cohesive, well-structured report
2. Write an executive summary at the beginning
3. Ensure smooth transitions between sections
4. Add a conclusion that synthesizes key takeaways
5. Include a references section with all sources
6. Use professional, clear language
7. Format with proper Markdown

The report should be comprehensive yet concise, suitable for a professional audience.
"""

REPORT_TEMPLATE = """# {title}

> Research Query: {query}
> Generated: {date}
> Research Iterations: {iterations}
> Total Cost: ${cost:.4f}

---

## Executive Summary

{summary}

---

## Table of Contents

{toc}

---

{body}

---

## Conclusion

{conclusion}

---

## References

{references}

---

*Generated by Deep Research Agent*
*Trace ID: {trace_id}*
"""


def writer_node(state: ResearchState) -> ResearchState:
    """Writer Agent node.

    Produces the final polished research report.

    Args:
        state: Current research state

    Returns:
        Updated state with final report
    """
    if not state.sections:
        state.add_log("ERROR", "No sections to write report from", agent="writer")
        state.report = f"# Error\n\nNo content generated for query: {state.query}"
        return state

    # Get model for strong tier (final writing requires quality)
    model, config = router.get_model(ModelTier.STRONG)

    try:
        # Prepare sections text
        sections_text = "\n\n".join([
            f"## {s.title}\n\n{s.content}"
            for s in sorted(state.sections, key=lambda x: x.order)
        ])

        # Generate the report body
        prompt = WRITER_PROMPT.format(
            query=state.query,
            sections=sections_text,
        )

        response = model.invoke(prompt)
        report_body = response.content if hasattr(response, 'content') else str(response)

        # Generate executive summary
        summary_prompt = f"""Summarize the following research report in 2-3 paragraphs:

{report_body[:3000]}

Executive Summary:"""

        summary_response = model.invoke(summary_prompt)
        summary = summary_response.content if hasattr(summary_response, 'content') else str(summary_response)

        # Generate conclusion
        conclusion_prompt = f"""Write a brief conclusion (1 paragraph) synthesizing the key takeaways:

{report_body[:3000]}

Conclusion:"""

        conclusion_response = model.invoke(conclusion_prompt)
        conclusion = conclusion_response.content if hasattr(conclusion_response, 'content') else str(conclusion_response)

        # Build table of contents
        toc = "\n".join([
            f"{i+1}. {s.title}"
            for i, s in enumerate(sorted(state.sections, key=lambda x: x.order))
        ])

        # Build references
        references = "\n".join([
            f"{i+1}. [{s.title}]({s.url})"
            for i, s in enumerate(state.sources[:20])  # Limit to top 20
        ])

        # Assemble final report
        state.report = REPORT_TEMPLATE.format(
            title=f"Research Report: {state.query[:50]}{'...' if len(state.query) > 50 else ''}",
            query=state.query,
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            iterations=state.iteration + 1,
            cost=state.cost.total_cost_usd,
            summary=summary,
            toc=toc,
            body=report_body,
            conclusion=conclusion,
            references=references,
            trace_id=state.trace_id,
        )

        # Track cost (all three calls)
        total_input_tokens = (
            router.estimate_tokens(prompt) +
            router.estimate_tokens(summary_prompt) +
            router.estimate_tokens(conclusion_prompt)
        )
        total_output_tokens = (
            router.estimate_tokens(report_body) +
            router.estimate_tokens(summary) +
            router.estimate_tokens(conclusion)
        )
        cost = router.calculate_cost(config, total_input_tokens, total_output_tokens)
        state.cost.add_call(config.name, total_input_tokens, total_output_tokens, cost)
        state.cost.add_agent_cost("writer", cost)

        state.add_log(
            "INFO",
            f"Report generated. Length: {len(state.report)} chars, Cost: ${state.cost.total_cost_usd:.4f}",
            agent="writer",
            report_length=len(state.report),
        )

    except Exception as e:
        state.add_log("ERROR", f"Writer failed: {str(e)}", agent="writer")
        # Fallback: combine sections manually
        state.report = f"# Research Report: {state.query}\n\n" + "\n\n".join([
            f"## {s.title}\n\n{s.content}"
            for s in state.sections
        ])

    return state
